name: autorun

on:
  workflow_dispatch:
  schedule:
    # 30分钟运行一次
    - cron: '0/30 * * * *'
    

jobs:
  ssh-and-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Check if service is running
      id: check_service
      run: |
        if curl --head --silent --fail https://memos.jimsblog.us.kg > /dev/null; then #这里改成你的Web服务的地址
          echo "service_status=running" >> $GITHUB_ENV
        else
          echo "service_status=not_running" >> $GITHUB_ENV
        fi

    - name: Run script on remote server if service is not running
      if: env.service_status == 'not_running'
      run: wget https://github.com/bet-io/Serv00-PM2-AutoRun-alist/raw/main/continue.sh & bash continue.sh  #这里改成你的用户名@你的s
